name: AI-GH-Pages Daily Content
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Generate content
        run: npm run generate
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit & Push
        run: |
          git config user.name "AI-GH-Pages Bot"
          git config user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "AI-GH-Pages: new daily post"
          git push
