name: Generate Daily AI Content

on:
  schedule:
    - cron: "0 6 * * *"  # Tous les jours à 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Generate Content
        run: node scripts/generate-content.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "AI Bot"
          git config --global user.email "aibot@users.noreply.github.com"
          git add .
          git commit -m "chore: add new daily post [skip ci]" || echo "No changes to commit"
          git push
